### ISSUE TITLE
[feature] Publish docker image?

### ISSUE THREAD

**Issue by decentral1se** [tldraw/tldraw-v1#96]
Would be great, especially for self-hosting options for tldraw :love_you_gesture:

**Comment by geekyouth** [comment]
https://hub.docker.com/r/geekyouth/tldraw

# docker

```
docker run --name tldraw -p 3000:3000 -d geekyouth/tldraw:2.0.0-alpha.18

```
OR

# docker compose
```
version: "3.9"

services:
  tldraw:
    image: geekyouth/tldraw:2.0.0-alpha.18
    hostname: tldraw
    container_name: tldraw-dev
    environment:
      TZ: Asia/Shanghai
    ports:
      - "3000:3000"

```

# Dockerfile
```
FROM node:16-alpine AS BASE

WORKDIR /app
COPY . .

RUN npm install --registry=https://registry.npmmirror.com

EXPOSE 3000

CMD ["npm", "run", "start"]

# docker run --name tldraw -p 3000:3000 -d geekyouth/tldraw:2.0.0-alpha.18

```
